### ISSUE TITLE
Find Data Sets

### ISSUE THREAD

**Issue by domgallo** [domgallo/CISC489#7]
ftp://ftp.cpc.ncep.noaa.gov/long/uv/cities

**Comment by adamltran** [comment]
http://scikit-learn.org/stable/auto_examples/linear_model/plot_polynomial_interpolation.html

Reference link for polynomial regression (since our data models a bell curve for each month)

**Comment by nayling** [comment]
The NOAA weather data from the first posted link was chosen for the project; we used the data from Dover, DE (labeled DOV) from the years 2006-2016.
