### ISSUE TITLE
Implement Machine Learning to make a prediction for UV Index

### ISSUE THREAD

**Issue by rbutler97** [domgallo/CISC489#9]
Possible methods: Linear Regression, Logistic Regression, Polynomial Regression, Neural Networks
(Use SciKit)

**Comment by rbutler97** [comment]
http://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessClassifier.html#sklearn.gaussian_process.GaussianProcessClassifier

**Comment by rbutler97** [comment]
Tried linear regression, but because the data forms approximately a bell curve every year, when we ran the algorithm it gave a line with no slope that returned approximately the average UV index for every data point.

**Comment by nayling** [comment]
Made extensive attempts with Gaussian process classification, which produced inaccurate results and would not work with a data set of over a year, as well as trying logistic regression, neural networks, and isotonic regression, none of which produced accurate results. We used the scikit library for all of these algorithms.
